name : Build

permissions:
  id-token: write
  contents: write

env:
  BuildConfiguration: Release
  DockerFilePath: ./src/ProjectName/Dockerfile
  DockerContext: ./src
  dotnet-version: 8.0.x
  WorkingDirectory: ./src/

on:
  workflow_dispatch:
  push:
    branches: 
      - $default-branch
  pull_request: 
    branches:
      - $default-branch

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.dotnet-version }}
    - name: Build Project
      working-directory: ${{env.WorkingDirectory}}
      run: dotnet build --configuration ${{ env.BuildConfiguration }}
    # - name: Run Tests
    #   working-directory: ${{env.WorkingDirectory}}
    #   run: dotnet test --configuration ${{ env.BuildConfiguration }} --logger GitHubActions
        
  
  dockerise:
    if: github.ref == 'refs/heads/main'
    name: Containerise and Push
    runs-on: ubuntu-latest
    needs: build-and-test
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: "Azure Login"
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID}}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: ACR Login
        run: az acr login --name ${{ vars.AZURE_CONTAINER_REGISTRY }}
      - name: Build and Push to Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/dev/${{ vars.AZURE_CONTAINER_IMAGE_NAME }}:${{ github.run_number }}
          context: ${{ env.DockerContext }}
          file: ${{ env.DockerFilePath }}
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"

      - name: Tag Release
        run: |
          git tag ${{ github.run_number }}
          git push origin ${{ github.run_number }}

  devdeploy:
    name: Deploy to Dev
    needs: dockerise
    uses: ./.github/workflows/deploy.yaml
    with:
      containerTag: ${{ github.run_number }}
      environment: 'Dev'
    secrets: inherit