name: Purge Containers

permissions:
  id-token: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3'  # Run every wednesday at midnight

jobs:
  purge_containers:
    name: Purge Containers
    uses: Soda-Digital/Deployment/.github/workflows/purge-containers.yaml@main

